# Generated by Django 3.2 on 2021-06-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_column='Perfil', max_length=40, verbose_name='Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('NomeProprio', models.CharField(max_length=255, verbose_name='Primeiro Nome')),
                ('SecondName', models.CharField(max_length=255, verbose_name='Apelido')),
                ('date_of_birth', models.DateField(default='1900-01-01')),
                ('n_telefone', models.IntegerField(default=900000001, unique=True, verbose_name='numero de telefone')),
                ('interno', models.BooleanField(default=False, null=True, verbose_name='interno')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.ForeignKey(db_column='roleid', on_delete=django.db.models.deletion.DO_NOTHING, to='users.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
