# Generated by Django 3.2 on 2021-05-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilizadores', '0001_initial'),
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='participanteutilizadorid',
            field=models.ForeignKey(blank=True, db_column='ParticipanteUtilizadorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utilizadores.participante'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tipo_de_eventoid',
            field=models.ForeignKey(db_column='Tipo de EventoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evento.tipodeevento'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tipo_de_formularioid',
            field=models.ForeignKey(db_column='Tipo de FormularioID', on_delete=django.db.models.deletion.DO_NOTHING, to='evento.tipodeformulario'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='eventoid',
            field=models.ForeignKey(db_column='EventoID', on_delete=django.db.models.deletion.DO_NOTHING, to='evento.evento'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='participanteutilizadorid',
            field=models.ForeignKey(blank=True, db_column='ParticipanteUtilizadorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utilizadores.participante'),
        ),
        migrations.AddField(
            model_name='evento',
            name='formulariofeedbackid',
            field=models.ForeignKey(db_column='FormularioFeedbackID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo', to='evento.formulario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='formularioinscricaoid',
            field=models.ForeignKey(db_column='FormularioInscricaoID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='capacidade', to='evento.formulario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='proponenteutilizadorid',
            field=models.ForeignKey(blank=True, db_column='ProponenteUtilizadorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utilizadores.proponente'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_de_eventoid',
            field=models.ForeignKey(db_column='TipoDeEventoID', on_delete=django.db.models.deletion.DO_NOTHING, to='evento.tipodeevento'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo_equipamentoid',
            field=models.ForeignKey(db_column='Tipo_EquipamentoID', on_delete=django.db.models.deletion.DO_NOTHING, to='evento.tipoequipamento'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='campusid',
            field=models.ForeignKey(db_column='CampusID', on_delete=django.db.models.deletion.DO_NOTHING, to='evento.campus'),
        ),
    ]
