# Generated by Django 3.1.7 on 2021-04-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='mobilidade_reduzida',
            field=models.BooleanField(db_column='Mobilidade reduzida'),
        ),
    ]
