# Generated by Django 3.1.7 on 2021-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20210413_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='fotos',
            field=models.ImageField(null=True, upload_to='Sala'),
        ),
    ]
