# Generated by Django 3.1.7 on 2021-04-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_auto_20210413_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='fotos',
            field=models.ImageField(db_column='Fotos', null=True, upload_to='evento/static/img'),
        ),
    ]
